name: Deploy to Rocky Linux VM

on:
  push:
    branches:
      - main  # Adjust this to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest  # Uses GitHub's Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checkout the repository code

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 192.168.199.128 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa denis@192.168.199.128 "echo 'Connection Successful!'"
