name: Deploy to Rocky Linux VM

on:
  push:
    branches:
      - main  # Adjust this to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest  # Uses GitHub's Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checkout the repository code

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Your private SSH key stored in GitHub secrets

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass  # Install sshpass to provide the password

      - name: Deploy to VM
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd /home/denis  # Replace with the directory where your app is located on the VM
            git pull origin main  # Pull the latest code from GitHub
            docker build -t website .  # Build the Docker image (replace 'website' with your image name)

            # Stop and remove the existing container (if it exists)
            docker ps -q -f name=website && docker stop website && docker rm website
            
            # Run the new container in detached mode
            docker run -d -p 8080:80 --name website website  # Give it a fixed name if you prefer
          EOF
